version: '3.9'
name: fiber-example
services:
  fiber-template:
    container_name: fiber-template
    build:
      context: ..
      dockerfile: Dockerfile.dev
    volumes:
      - ./../:/app
    command: sleep infinity
    depends_on:
      - postgres-db

  postgres-db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis-db:
    build:
      context: ./redis  # Llama al Dockerfile que hemos creado en ./redis
      dockerfile: Dockerfile
    container_name: redis-db
    ports:
      - "6379:6379"  # Exponer el puerto 6379 para Redis
    volumes:
      - redis_data:/data  # Volumen para persistir datos de Redis
    restart: always
    depends_on:
      - postgres-db

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local