version: '3.9'
name: fiber-example
services:
  fiber-template:
    container_name: fiber-template
    ports:
      - "4001:4001"
    build:
      context: ..
      dockerfile: Dockerfile.dev
    volumes:
      - ./../:/app
    command: sleep infinity
    depends_on:
      - postgres-db

  postgres-db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local